enum MessageEnum {
  INVALID_REQUEST = "Invalid Request Created",
  RECORD_NOT_FOUND = "Record Not Found",
  INVALID_USER_ID = "Invalid User Id",
  INVALID_EMAIL = "Invalid Email!",
  INVALID_CODE = "Invalid Code!",
  SET_YOUR_PASSWORD = "Please set you password first!!",
  INVALID_CREDENTIALS = " Invalid credentials",
  EMAIL_ALREADY_EXIST = "Email Already Exist",
  SLUG_ALREADY_EXIST = "Slug Already Exist",
  RECORD_NOT_FOUND_WITH_SLUG = "Record not found with this slug",
  INVALID_CATEGORY = "Invalid Category",
  INVALID_SUBCATEGORY = "Invalid SubCategory",
  NAME_ALREADY_EXIST = "Name Already Exist",
  SUCCESSFULLY = "Successfully",
  ALREADY_SUBSCRIBED = "You have already subscribed",
  SUBSCRIBE_SUCCESSFULLY = "Thank you for subscribing Tam",
  CONTACTUS_SUCCESSFULLY = "Thank you for contacting us",
  ALREADY_EXIST = "Already exists",
  MAXIMUM_SELECTED = "Please remove one from featured to select new!",
  ARTICLES_ARE_REQUIRED = "Articles are Required!",
  COURSES_ARE_REQUIRED = "Courses are Required!",
  CANNOT_DELETE_THIS_ARTICLE = "You cannot delete this article",
  CANNOT_DELETE_THIS_COURSE = "You cannot delete this course",
  INVALID_OLD_PASSWORD = "Old password does not match!",
  ACCOUNT_SUSPENDED = "Your account has been suspended!",
}

export default MessageEnum;
